name: Deploy Packages own

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build idb_companion
        run: |
          cd $GITHUB_WORKSPACE
          brew install xcodegen protobuf swift-protobuf grpc-swift
          ./build.sh build idb_companion

      - name: Compress idb_companion
        run: |
          tar -czf idb-companion.universal.tar.gz -C /build/Build/Products/Release

      - name: Upload idb_companion Artifact
        uses: actions/upload-artifact@v4
        with:
          name: idb_companion
          path: ./idb-companion.universal.tar.gz
